import { Language, Publication } from '../types'

export const LANG_CS: Language = 'cs'
export const LANG_EN: Language = 'en'
export const LANG_DE: Language = 'de'
export const LANG_IT: Language = 'it'

export const BASE_URL = 'https://tyrovsti.cz'

export const BACKGROUND_IMAGES = [
  '/images/background/background1.webp',
  '/images/background/background2.webp',
  '/images/background/background3.webp',
  '/images/background/background4.webp',
]

export const PUBLICATIONS: Record<string, Publication> = {
  KURSCHNER: {
    name: 'Jobst von Einsiedel und seine Correspondenz mit der Stadt Eger. Aus dem Archive der Stadt Eger',
    author: 'Franz Kürschner',
    city: { cs: 'Vídeň', en: 'Vienna', de: 'Wien', it: 'Vienna' },
    year: 1868,
  },
  KOCKA: {
    name: 'Dějiny Rakovnicka',
    author: 'Václav Kočka',
    city: 'Rakovník',
    year: 2009,
  },
  KOCKA1: {
    name: 'Dějiny politického okresu kralovického. Díl 1. Soudní okres kralovický',
    author: 'Václav Kočka',
    city: 'Kralovice',
    year: 1930,
    href: 'https://kramerius5.nkp.cz/view/uuid:cbd24070-4608-11ed-b64c-005056827e52',
  },
  KOCKA30: {
    name: 'Kralovicko za války třicetileté',
    author: 'Václav Kočka',
    city: 'Kralovice u Plzně',
    year: 1922,
    href: 'https://kramerius5.nkp.cz/view/uuid:9bfe6dc0-47ef-11ea-81b3-005056827e52',
  },
  SEDLACEK8: {
    name: 'Hrady, zámky a tvrze království Českého. Díl VIII. Rakovnicko a Slánsko',
    author: 'August Sedláček',
    city: 'Praha',
    year: 1891,
    href: 'https://kramerius5.nkp.cz/view/uuid:1ed20270-2ffb-11de-8f63-000d606f5dc6',
  },
  SEDLACEK13: {
    name: 'Hrady, zámky a tvrze království Českého. Díl XIII. Plzeňsko a Loketsko',
    author: 'August Sedláček',
    city: 'Praha',
    year: 1905,
    href: 'https://kramerius5.nkp.cz/view/uuid:12f8f660-3001-11de-b49a-000d606f5dc6',
  },
  SEDLACEK_HERALDIKA1: {
    name: 'Českomoravská heraldika. Část všeobecná',
    author: 'August Sedláček',
    city: 'Praha',
    year: 1902,
    href: 'https://kramerius5.nkp.cz/view/uuid:d6b3bfb0-3f08-11e4-bc3a-005056827e51',
  },
  SEDLACEK_HERALDIKA2: {
    name: 'Českomoravská heraldika. Část zvláštní',
    author: 'August Sedláček',
    city: 'Praha',
    year: 1925,
    href: 'https://kramerius5.nkp.cz/view/uuid:b5251ae0-2457-11e4-8e0d-005056827e51',
  },
  OTTO25: {
    name: 'Ottův slovník naučný. Díl XXV. T–Tzschirner (heslo Tejřovský z Enzidle, autor August Sedláček)',
    author: 'Jan Otto (vyd.)',
    city: 'Praha',
    year: 1906,
    href: 'https://kramerius5.nkp.cz/view/uuid:7e11fe20-043e-11e5-95ff-5ef3fc9bb22f',
  },
  OTTO14: {
    name: 'Ottův slovník naučný. Díl XIV. Kartel–Kraj (heslo Kožlany)',
    author: 'Jan Otto (vyd.)',
    city: 'Praha',
    year: 1899,
    href: 'https://kramerius5.nkp.cz/view/uuid:7e11fe20-043e-11e5-95ff-5ef3fc9bb22f',
  },
  MERAVIGLIA: {
    name: 'J. Siebmacher’s grosses und allgemeines Wappenbuch. IV. Band, 9. Abteilung: Der Böhmische Adel',
    author: 'Rudolf Johann Meraviglia-Crivelli',
    city: 'Nürnberg',
    year: 1886,
    href: 'https://archive.org/details/deradelvonbhme00kral',
  },
  KRAL_HERALDIKA: {
    name: 'Heraldika. Souhrn pravidel a předpisův znakových',
    author: 'Vojtěch Král z Dobré Vody',
    city: 'Praha',
    year: 1900,
  },
  PAPROCKY: {
    name: 'Diadochos id est successio, jinák posloupnost knížat a králův českých, biskupův i arcibiskupův pražských a všech třech stavův slavného království českého',
    author: 'Bartoloměj Paprocký z Hlohol',
    city: 'Praha',
    year: 1602,
    href: 'https://books.google.com/books?id=mh5fAAAAcAAJ&pg=RA1-PA346',
  },
  SNEMY1: {
    name: 'Sněmy české od léta 1526 až po naši dobu. Díl I. 1526–1545',
    author: 'Královský český archiv zemský (vyd.)',
    city: 'Praha',
    year: 1877,
    href: 'https://www.psp.cz/eknih/snemy/v010/index.htm',
  },
  SNEMY2: {
    name: 'Sněmy české od léta 1526 až po naši dobu. Díl II. 1546–1557',
    author: 'Královský český archiv zemský (vyd.)',
    city: 'Praha',
    year: 1880,
    href: 'https://www.psp.cz/eknih/snemy/v020/index.htm',
  },
  SNEMY3: {
    name: 'Sněmy české od léta 1526 až po naši dobu. Díl III. 1558–1573',
    author: 'Královský český archiv zemský (vyd.)',
    city: 'Praha',
    year: 1884,
    href: 'https://www.psp.cz/eknih/snemy/v030/index.htm',
  },
  SNEMY4: {
    name: 'Sněmy české od léta 1526 až po naši dobu. Díl IV. 1574–1576',
    author: 'Královský český archiv zemský (vyd.)',
    city: 'Praha',
    year: 1886,
    href: 'https://www.psp.cz/eknih/snemy/v040/index.htm',
  },
  SNEMY5: {
    name: 'Sněmy české od léta 1526 až po naši dobu. Díl V. 1577–1580',
    author: 'Královský český archiv zemský (vyd.)',
    city: 'Praha',
    year: 1887,
    href: 'https://www.psp.cz/eknih/snemy/v050/index.htm',
  },
  SNEMY7: {
    name: 'Sněmy české od léta 1526 až po naši dobu. Díl VII. 1586–1591',
    author: 'Královský český archiv zemský (vyd.)',
    city: 'Praha',
    year: 1891,
    href: 'https://www.psp.cz/eknih/snemy/v070/index.htm',
  },
  SNEMY8: {
    name: 'Sněmy české od léta 1526 až po naši dobu. Díl VIII. 1592–1594',
    author: 'Královský český archiv zemský (vyd.)',
    city: 'Praha',
    year: 1895,
    href: 'https://www.psp.cz/eknih/snemy/v080/index.htm',
  },
  SNEMY9: {
    name: 'Sněmy české od léta 1526 až po naši dobu. Díl IX. 1595–1599',
    author: 'Královský český archiv zemský (vyd.)',
    city: 'Praha',
    year: 1897,
    href: 'https://www.psp.cz/eknih/snemy/v090/index.htm',
  },
  SNEMY10: {
    name: 'Sněmy české od léta 1526 až po naši dobu. Díl X. 1600–1604',
    author: 'Královský český archiv zemský (vyd.)',
    city: 'Praha',
    year: 1900,
    href: 'https://www.psp.cz/eknih/snemy/v100/index.htm',
  },
  SNEMY11: {
    name: 'Sněmy české od léta 1526 až po naši dobu. Díl XI. 1605–1607',
    author: 'Zemský výbor království Českého (vyd.)',
    city: 'Praha',
    year: 1910,
    href: 'https://www.psp.cz/eknih/snemy/v11a/index.htm',
  },
  AC4: {
    name: 'Archiv český čili staré písemné památky české i moravské. Díl IV',
    author: 'František Palacký (ed.)',
    city: 'Praha',
    year: 1846,
    href: 'https://kramerius5.nkp.cz/view/uuid:d1ba97d0-8dd4-11e8-9588-5ef3fc9bb22f',
  },
  AC7: {
    name: 'Archiv český čili staré písemné památky české i moravské. Díl VII',
    author: 'Josef Kalousek (ed.)',
    city: 'Praha',
    year: 1887,
    href: 'https://kramerius5.nkp.cz/view/uuid:597c2280-8dd8-11e8-9588-5ef3fc9bb22f',
  },
  AC10: {
    name: 'Archiv český čili staré písemné památky české i moravské. Díl X',
    author: 'Josef Kalousek (ed.)',
    city: 'Praha',
    year: 1890,
    href: 'https://kramerius5.nkp.cz/view/uuid:9f1e2c80-8dd7-11e8-9588-5ef3fc9bb22f',
  },
  AC11: {
    name: 'Archiv český čili staré písemné památky české i moravské. Díl XI',
    author: 'Josef Kalousek (ed.)',
    city: 'Praha',
    year: 1892,
    href: 'https://kramerius5.nkp.cz/view/uuid:fb8d8100-8dd7-11e8-9588-5ef3fc9bb22f',
  },
  AC13: {
    name: 'Archiv český čili staré písemné památky české i moravské. Díl XIII',
    author: 'Josef Kalousek (ed.)',
    city: 'Praha',
    year: 1894,
    href: 'https://kramerius5.nkp.cz/view/uuid:76149be0-8dd6-11e8-9588-5ef3fc9bb22f',
  },
  AC15: {
    name: 'Archiv český čili staré písemné památky české i moravské. Díl XV',
    author: 'Josef Kalousek (ed.)',
    city: 'Praha',
    year: 1896,
    href: 'https://kramerius5.nkp.cz/view/uuid:c2007dd0-8dd6-11e8-9588-5ef3fc9bb22f',
  },
  AC19: {
    name: 'Archiv český čili staré písemné památky české i moravské. Díl XIX',
    author: 'Josef Kalousek (ed.)',
    city: 'Praha',
    year: 1901,
    href: 'https://kramerius5.nkp.cz/view/uuid:4d1a50b0-8dd9-11e8-9588-5ef3fc9bb22f',
  },
  AC37: {
    name: 'Archiv český čili staré písemné památky české i moravské. Díl XXXVII. Čtvrtá kniha provolací desk dvorských z let 1453–1480',
    author: 'Gustav Friedrich (ed.)',
    city: 'Praha',
    year: 1941,
    href: 'https://kramerius5.nkp.cz/view/uuid:ecb030a0-9567-11e8-87bd-005056827e52',
  },
  ZBYTKY: {
    name: 'Zbytky register králův římských a českých z let 1361–1480',
    author: 'August Sedláček',
    city: 'Praha',
    year: 1914,
    href: 'https://kramerius5.nkp.cz/view/uuid:4a255040-84f9-11e4-9d8c-005056827e51',
  },
  TEIGE_LISTAR: {
    name: 'Drobné příspěvky k českému listáři',
    author: 'Josef Teige',
    city: 'Praha',
    year: 1887,
    href: 'https://kramerius5.nkp.cz/view/uuid:8e3d4b30-7bb8-11e7-8b50-001018b5eb5c',
  },
  TEIGE_MISTOPIS: {
    name: 'Základy starého místopisu Pražského (1437–1620). Oddíl I. Staré město pražské. Díl I',
    author: 'Josef Teige',
    city: 'Praha',
    year: 1910,
    href: 'https://kramerius5.nkp.cz/view/uuid:c4adae90-89cb-11e3-bd09-005056827e51',
  },
  BILEK: {
    name: 'Dějiny konfiskací v Čechách po r. 1618',
    author: 'Tomáš V. Bílek',
    city: 'Praha',
    year: 1882,
    href: 'https://kramerius5.nkp.cz/view/uuid:ca6e5cc0-e117-11dc-9e25-000d606f5dc6',
  },
  MILITARE5: {
    name: 'Prameny k dějinám třicetileté války. Regesta fondu Militare archivu Ministerstva vnitra ČSR v Praze. Díl V. 1636–1639',
    author: 'Václav Líva (ed.)',
    city: 'Praha',
    year: 1955,
    href: 'https://kramerius5.nkp.cz/view/uuid:ce02ccf0-c3af-11e3-bb44-5ef3fc9bb22f',
  },
  MILITARE6: {
    name: 'Prameny k dějinám třicetileté války. Regesta fondu Militare archivu Ministerstva vnitra ČSR v Praze. Díl VI. 1640–1642',
    author: 'Václav Líva (ed.)',
    city: 'Praha',
    year: 1955,
    href: 'https://kramerius5.nkp.cz/view/uuid:ce02ccf0-c3af-11e3-bb44-5ef3fc9bb22f',
  },
  MILITARE7: {
    name: 'Prameny k dějinám třicetileté války. Regesta fondu Militare archivu Ministerstva vnitra ČSR v Praze. Díl VII. 1643–1645',
    author: 'Václav Líva (ed.)',
    city: 'Praha',
    year: 1955,
    href: 'https://kramerius5.nkp.cz/view/uuid:ce02ccf0-c3af-11e3-bb44-5ef3fc9bb22f',
  },
  TILIA: {
    name: 'Chronicon Plassense „Tilia Plassensis“. Pars III',
    author: 'Klášter Plasy',
    city: 'Praha',
    year: 1909,
    href: 'https://kramerius5.nkp.cz/view/uuid:46c7f19b-ec76-11f0-897f-72b499cdd859',
  },
  PODLAHA_REF: {
    name: 'Protokol reformační kommisse, konané l. 1628 v krajích Bechyňském, Prachenském a Plzenském',
    author: 'Antonín Podlaha (ed.)',
    city: 'Praha',
    year: 1897,
  },
  PA1876: {
    name: 'Památky archaeologické a místopisné. Díl X (1874–1877). Zprávy a drobnosti: Seznam krajských hejtmanů',
    author: 'Archaeologický sbor Musea království Českého',
    city: 'Praha',
    year: 1876,
    href: 'https://kramerius5.nkp.cz/view/uuid:be359a80-ce5a-11e4-9c07-5ef3fc9bb22f',
  },
  PA1875: {
    name: 'Památky archaeologické a místopisné. Díl X (1874–1877). Zprávy a drobnosti: Seznam krajských hejtmanů (pokračování)',
    author: 'Archaeologický sbor Musea království Českého',
    city: 'Praha',
    year: 1875,
    href: 'https://kramerius5.nkp.cz/view/uuid:be359a80-ce5a-11e4-9c07-5ef3fc9bb22f?page=uuid:cc9a3a90-d8b4-11e4-a19f-001018b5eb5c',
  },
  WINTER_RAKOBR2: {
    name: 'Rakovnické obrázky. Ze života XVI. stol. Řada druhá',
    author: 'Zikmund Winter',
    city: 'Praha',
    year: 1912,
    href: 'https://kramerius5.nkp.cz/view/uuid:fa363310-60f9-11e9-ace0-005056827e51',
  },
  WINTER_KULT2: {
    name: 'Kulturní obraz českých měst. Život veřejný v XV. a XVI. věku. Díl druhý',
    author: 'Zikmund Winter',
    city: 'Praha',
    year: 1892,
    href: 'https://kramerius5.nkp.cz/view/uuid:f72f4b00-98d5-11dc-8990-000d606f5dc6',
  },
  WINTER_SKOLY: {
    name: 'Život a učení na partikulárních školách v Čechách v XV. a XVI. století',
    author: 'Zikmund Winter',
    city: 'Praha',
    year: 1901,
    href: 'https://kramerius5.nkp.cz/view/uuid:4c490d60-e6c2-11e8-8d10-5ef3fc9ae867',
  },
  TRESP: {
    name: 'Söldner aus Böhmen: im Dienst deutscher Fürsten: Kriegsgeschäft und Heeresorganisation im 15. Jahrhundert',
    author: 'Uwe Tresp',
    city: 'Paderborn',
    year: 2004,
  },
  JANSKY: {
    name: 'Kronika česko-bavorské hranice III',
    author: 'Jiří Jánský',
    city: 'Domažlice',
    year: 2003,
  },
  SLADKOVSKA: {
    name: 'Česká účast ve válce o dědictví landshutské roku 1504',
    author: 'Kamila Sladkovská',
    city: { cs: 'Tábor', en: 'Tábor', de: 'Tabor', it: 'Tábor' },
    year: 2009,
    href: 'https://rukovet.cms.flu.cas.cz/static/Odkazy_upload/HT_16_2009.pdf',
  },
  SEDLACEK1: {
    name: 'Zbytky register králů římských a českých z let 1361-1480',
    author: 'August Sedláček',
    city: { cs: 'Praha', en: 'Prague', de: 'Prag', it: 'Praga' },
    year: 1914,
  },
  BOUKAL: {
    name: 'Víra a společnost v českých zemích pozdního středověku. K dějinám společenských proměn a náboženského konfliktu 14.–16. století',
    author: 'Kajetán Holeček, David Trojan (ed.)',
    city: { cs: 'Praha', en: 'Prague', de: 'Prag', it: 'Praga' },
    year: 2026,
  },
  BOUKAL1: {
    name: 'Vztahy města Cheb a české šlechty v pozdním středověku',
    author: 'Jan Boukal',
    city: { cs: 'Praha', en: 'Prague', de: 'Prag', it: 'Praga' },
    year: 2021,
    href: 'https://dspace.cuni.cz/bitstream/handle/20.500.11956/171445/140096911.pdf',
  },
  PELANT: {
    name: 'Erby české, moravské a slezské šlechty',
    author: 'Jan Pelant',
    city: { cs: 'Praha', en: 'Prague', de: 'Prag', it: 'Praga' },
    year: 2013,
  },
  FELCMAN: {
    name: 'PODĚBRADOVÉ Rod českomoravských pánů, kladských hrabat a slezských knížat',
    author:
      'Ondřej Felcman, Radek Fukala, Vladimír Hrubý, Jarosław Malicki, Karel Müller, František Musil, Miroslav Plaček, Jaroslav Šůla, Martin Šandera, Marek Vařeka',
    city: { cs: 'Praha', en: 'Prague', de: 'Prag', it: 'Praga' },
    year: 2008,
  },
  MACEK: {
    name: 'Jiří z Poděbrad',
    author: 'Josef Macek',
    city: { cs: 'Praha', en: 'Prague', de: 'Prag', it: 'Praga' },
    year: 1967,
  },
  FEYFRLIKOVA: {
    name: 'Proměna stylu odívání v průběhu husitských válek',
    author: 'Monika Feyfrlíková',
    city: { cs: 'Praha', en: 'Prague', de: 'Prag', it: 'Praga' },
    year: 2017,
    href: 'https://dspace.cuni.cz/bitstream/handle/20.500.11956/92944/DPTX_2014_2_11210_0_436502_0_166872.pdf',
  },
  FEYFRLIKOVA2: {
    name: 'Móda a odívání v husitské době',
    author: 'Monika Feyfrlíková Černá',
    city: { cs: 'Praha', en: 'Prague', de: 'Prag', it: 'Praga' },
    year: 2020,
  },
  GOUBITZ: {
    name: 'Stepping Through Time: Archaeological Footwear from Prehistoric Times until 1800',
    author: 'Olaf Goubitz',
    city: 'Zwolle',
    year: 2007,
  },
  WINTER: {
    name: 'Dějiny kroje v zemích českých od počátku století 15. až po dobu Bělohorské bitvy',
    author: 'Zikmund Winter',
    city: { cs: 'Praha', en: 'Prague', de: 'Prag', it: 'Praga' },
    year: 1893,
  },
  WINTER2: {
    name: 'Dějiny řemesel a obchodu v Čechách v XIV. a v XV. století',
    author: 'Zikmund Winter',
    city: { cs: 'Praha', en: 'Prague', de: 'Prag', it: 'Praga' },
    year: 1906,
  },
  PILNA: {
    name: 'Oděv v západních Čechách 15. až 17. století',
    author: 'Veronika Pilná',
    city: 'Plzeň',
    year: 2018,
  },
  EMBLETON: {
    name: 'Europa Militaria Special No 8 - Medieval Military Costume Recreated in Colour Photographs',
    author: 'Gerry Embleton',
    city: 'Ramsbury',
    year: 2000,
  },
  PAPAJIK: {
    name: 'Ladislav Pohrobek (1440 - 1457) uherský a český král',
    author: 'David Papajík',
    city: 'České Budějovice',
    year: 2016,
  },
  BUBEN: {
    name: 'Encyklopedie heraldiky',
    author: 'Milan Buben',
    city: { cs: 'Praha', en: 'Prague', de: 'Prag', it: 'Praga' },
    year: 1999,
  },
  ARCHIV8: {
    name: 'Archiv český čili staré písemné památky české i moravské VIII',
    author: 'Josef Kalousek, Královská česká společnost nauk',
    city: { cs: 'Praha', en: 'Prague', de: 'Prag', it: 'Praga' },
    year: 1888,
  },
  ARCHIV14: {
    name: 'Archiv český čili staré písemné památky české i moravské XIV',
    author:
      'Josef Kalousek, František Dvorský, Vácslav Vladivoj Tomek, Josef Emler',
    city: { cs: 'Praha', en: 'Prague', de: 'Prag', it: 'Praga' },
    year: 1895,
  },
  WEDGWOOD: {
    name: 'On False Etymologies',
    author: 'Hensleigh Wedgwood',
    city: { cs: 'Londýn', en: 'London', de: 'London', it: 'Londra' },
    year: 1855,
  },
  ALEX: {
    name: 'Alexandreida',
    author: '',
    city: { cs: 'Praha', en: 'Prague', de: 'Prag', it: 'Praga' },
    year: 1963,
    href: 'https://dl1.cuni.cz/pluginfile.php/1094538/mod_resource/content/1/Alexandreida%20%281963%29.pdf',
  },
  KRONIKAPEKNA: {
    name: 'Kronika velmi pěkná o Janu Žižkovi',
    author: '',
    city: '',
    year: undefined,
    href: 'https://husitstvi.cz/historie/dobove-dokumenty/kronika-velmi-pekna-o-janu-zizkovi-1434-1436/',
  },
  GEBAUER: {
    name: 'Slovník staročeský',
    author: 'Jan Gebauer',
    city: { cs: 'Praha', en: 'Prague', de: 'Prag', it: 'Praga' },
    year: 1970,
  },
  PATALA: {
    name: 'Pod znakiem świętego Sebalda. Rola Norymbergi w kształtowaniu późnogotyckiego malarstwa tablicowego na Śląsku',
    author: 'Agnieszka Patała',
    city: 'Wrocław',
    year: 2018,
  },
  DENKSTEIN3: {
    name: 'Pavézy českého typu. III. Pavézy v českých historických pramenech',
    author: 'Vladimír Denkstein',
    city: { cs: 'Praha', en: 'Prague', de: 'Prag', it: 'Praga' },
    year: 1965,
  },
  BROZEK: {
    name: 'Platnéřství',
    author: 'Petr Brožek',
    city: { cs: 'Praha', en: 'Prague', de: 'Prag', it: 'Praga' },
    year: 2021,
  },
  ACADEMIA: {
    name: 'Staročeský slovník',
    author: 'Academia',
    city: { cs: 'Praha', en: 'Prague', de: 'Prag', it: 'Praga' },
    year: 2008,
  },
  HALADA: {
    name: 'Lexikon české šlechty II erby, fakta, osobnosti, sídla a zajímavosti',
    author: 'Jan Halada',
    city: { cs: 'Praha', en: 'Prague', de: 'Prag', it: 'Praga' },
    year: 1993,
  },
  POSPISIL: {
    name: 'Festivity v době pobytů Jiřího z Poděbrad v Chebu',
    author: 'Přemysl Pospíšil',
    city: { cs: 'Praha', en: 'Prague', de: 'Prag', it: 'Praga' },
    year: 2010,
    href: 'http://encyklopedie.cheb.cz/administrace/soubory_varia/1526546827_cz_19__festivity_v_dobe_pobytu_jiriho_z_podebrad_v_chebu.pdf',
  },
  TOMIC: {
    name: 'curiavitkov.cz',
    author: 'Ladislav Tomič',
    city: '',
    year: 2004,
    href: 'https://curiavitkov.cz/',
  },
  TALAGA: {
    name: `A Kampfschwert from the 15th century a reinterpretation of the so called 'Teutonic estoc' from the Princes Czartoryski Collection in Cracow, Poland`,
    author: 'Maciej Talaga',
    city: { cs: 'Varšava', en: 'Warsaw', de: 'Warschau', it: 'Varsavia' },
    year: 2013,
    href: "https://www.researchgate.net/publication/290777603_A_Kampfschwert_from_the_15th_century_-_a_reinterpretation_of_the_so_called_'Teutonic_estoc'_from_the_Princes_Czartoryski_Collection_in_Cracow_Poland",
  },
  RA: {
    name: 'royalarmouries.org',
    author: '',
    city: { cs: 'Londýn', en: 'London', de: 'London', it: 'Londra' },
    year: undefined,
    href: 'https://royalarmouries.org/',
  },
  VONHARSDORF: {
    name: 'vonharsdorf.de',
    author: '',
    city: '',
    year: undefined,
    href: 'http://vonharsdorf.de/',
  },
  ENCYKLOPEDIEPLZEN: {
    name: 'encyklopedie.plzen.eu',
    author: '',
    city: '',
    year: undefined,
  },
  WIKI: {
    name: 'wikipedia.org',
    author: '',
    city: '',
    year: undefined,
  },
  NOVINKY: {
    name: 'novinky.cz',
    author: '',
    city: '',
    year: undefined,
  },
  CMSKH: {
    name: 'cms-kh.cz',
    author: '',
    city: '',
    year: undefined,
  },
  SECKENHEIM: {
    name: 'historisches-seckenheim.de',
    author: '',
    city: '',
    year: undefined,
  },
  RAZIM1: {
    name: 'Přemyslovské Křivoklátsko. 900 let hradu Křivoklátu',
    author: 'Vladislav Razím',
    city: 'Praha',
    year: 2010,
  },
  NOVOTNA: {
    name: 'Listiny tepelského kláštera v letech 1300 až 1419',
    author: 'Marie Novotná',
    city: 'Praha',
    year: 2024,
    href: 'https://dspace.cuni.cz/bitstream/handle/20.500.11956/192344/130393934.pdf',
  },
  PAYNE: {
    name: 'Genealogie šlechtických rodů',
    author: 'Miroslav Marek (payne.cz)',
    city: '',
    year: undefined,
    href: 'https://www.payne.cz/',
  },
  HOLICKI_THESIS: {
    name: 'Aleš a Petr Holičtí ze Šternberka v politice první poloviny 15. století',
    author: 'rigorózní práce, Univerzita Karlova',
    city: 'Praha',
    year: undefined,
    href: 'https://dspace.cuni.cz/handle/20.500.11956/96114',
  },
  CALLIMACHUS_VARNENSI: {
    name: 'Historia de rege Vladislao seu clade Varnensi',
    author: 'Filippo Buonaccorsi (Callimachus)',
    city: 'Augsburg',
    year: 1519,
    href: 'https://archive.org/details/jbc.bj.uj.edu.pl.NDIGSTDR009201',
  },
  DLUGOSZ: {
    name: 'Annales seu cronicae incliti Regni Poloniae',
    author: 'Jan Długosz',
    city: { cs: 'Krakov', en: 'Kraków', de: 'Krakau', it: 'Cracovia' },
    year: 1480,
  },
  BONFINI: {
    name: 'Rerum Hungaricarum decades',
    author: 'Antonio Bonfini',
    city: { cs: 'Basilej', en: 'Basel', de: 'Basel', it: 'Basilea' },
    year: 1568,
  },
  AENEAS_BOHEMICA: {
    name: 'Historia Bohemica',
    author: 'Aeneas Silvius Piccolomini (Pius II.)',
    city: { cs: 'Řím', en: 'Rome', de: 'Rom', it: 'Roma' },
    year: 1458,
  },
  KROMER: {
    name: 'De origine et rebus gestis Polonorum libri XXX',
    author: 'Marcin Kromer',
    city: { cs: 'Basilej', en: 'Basel', de: 'Basel', it: 'Basilea' },
    year: 1555,
  },
  BYCHOWIEC: {
    name: 'Kronika litewska (tzv. Bychowiec Chronicle)',
    author: 'anonymní autor / Bychowiec',
    city: { cs: 'Litva', en: 'Lithuania', de: 'Litauen', it: 'Lituania' },
    year: undefined,
  },
  STARI_LETOPISOVE: {
    name: 'Staří letopisové čeští',
    author: 'soubor anonymních kronikářů 15. století',
    city: { cs: 'Praha', en: 'Prague', de: 'Prag', it: 'Praga' },
    year: undefined,
  },
  GALEOTTO: {
    name: 'De egregie, sapienter, iocose dictis ac factis regis Mathiae',
    author: 'Galeotto Marzio',
    city: { cs: 'Vídeň', en: 'Vienna', de: 'Wien', it: 'Vienna' },
    year: 1485,
  },
  ARNPECK: {
    name: 'Chronicon Bavarorum',
    author: 'Veit Arnpeck',
    city: { cs: 'Mnichov', en: 'Munich', de: 'München', it: 'Monaco' },
    year: 1495,
  },
  THUROCZY: {
    name: 'Chronica Hungarorum',
    author: 'János Thuróczy',
    city: {
      cs: 'Brno / Augsburg',
      en: 'Brno / Augsburg',
      de: 'Brünn / Augsburg',
      it: 'Brno / Augusta',
    },
    year: 1488,
  },
  KONSTANTIN_OSTROVICE: {
    name: 'Türkenchronik (Pamiętniki janczara)',
    author: 'Konstantin z Ostrovice',
    city: {
      cs: 'Polsko / Srbsko',
      en: 'Poland / Serbia',
      de: 'Polen / Serbien',
      it: 'Polonia / Serbia',
    },
    year: 1497,
  },
  ERBEN: {
    name: 'Wýbor z literatury české II',
    author: 'Karel Jaromír Erben',
    city: { cs: 'Praha', en: 'Prague', de: 'Prag', it: 'Praga' },
    year: 1868,
    href: 'https://kramerius5.nkp.cz/view/uuid:3d010e30-967d-11dc-a3f5-000d606f5dc6',
  },
  TOMAN: {
    name: 'Husitské válečnictví za doby Žižkovy a Prokopovy',
    author: 'Hugo Toman',
    city: { cs: 'Praha', en: 'Prague', de: 'Prag', it: 'Praga' },
    year: 1898,
    href: 'https://kramerius5.nkp.cz/view/uuid:0723c370-14ea-11dd-959f-000d606f5dc6',
  },
  CORNEJ: {
    name: 'Jan Žižka: Život a doba husitského válečníka',
    author: 'Petr Čornej',
    city: { cs: 'Praha', en: 'Prague', de: 'Prag', it: 'Praga' },
    year: 2019,
  },
  VAVRINEC: {
    name: 'Husitská kronika',
    author: 'Vavřinec z Březové',
    city: { cs: 'Praha', en: 'Prague', de: 'Prag', it: 'Praga' },
    year: 1979,
  },
  DURDIK: {
    name: 'Husitské vojenství',
    author: 'Jan Durdík',
    city: { cs: 'Praha', en: 'Prague', de: 'Prag', it: 'Praga' },
    year: 1953,
  },
  VYBOR1: {
    name: 'Výbor z české literatury doby husitské I',
    author: 'Bohuslav Havránek, Josef Hrabák, Jiří Daňhelka (ed.)',
    city: { cs: 'Praha', en: 'Prague', de: 'Prag', it: 'Praga' },
    year: 1963,
  },
  JISTEBNICE: {
    name: 'Jistebnický kancionál (Knihovna Národního muzea, sign. II C 7)',
    author: '',
    city: '',
    year: undefined,
  },
  DRA9: {
    name: 'Deutsche Reichstagsakten unter Kaiser Sigmund. Dritte Abtheilung: 1427–1431 (Deutsche Reichstagsakten IX)',
    author: 'Dietrich Kerler (ed.)',
    city: 'Gotha',
    year: 1887,
    href: 'https://www.digitale-sammlungen.de/de/view/bsb11833357',
  },
  TOEPPEN1: {
    name: 'Acten der Ständetage Preussens unter der Herrschaft des Deutschen Ordens I',
    author: 'Max Toeppen (ed.)',
    city: { cs: 'Lipsko', en: 'Leipzig', de: 'Leipzig', it: 'Lipsia' },
    year: 1878,
    href: 'https://kpbc.umk.pl/dlibra/publication/9560/edition/21483/content',
  },
  KOHLER3: {
    name: 'Die Entwickelung des Kriegswesens und der Kriegführung in der Ritterzeit III/2',
    author: 'Gustav Köhler',
    city: { cs: 'Vratislav', en: 'Breslau', de: 'Breslau', it: 'Breslavia' },
    year: 1889,
    href: 'https://archive.org/details/dieentwickelung02khgoog',
  },
  DRA17: {
    name: 'Deutsche Reichstagsakten unter Kaiser Friedrich III. Dritte Abteilung: 1442–1445 (Deutsche Reichstagsakten XVII)',
    author: 'Walter Kaemmerer (ed.)',
    city: 'Göttingen',
    year: 1963,
    href: 'https://sources.cms.flu.cas.cz/src/index.php?s=v&bookid=506',
  },
  WULCKER: {
    name: 'Urkunden und Schreiben betreffend den Zug der Armagnaken (1439–1444)',
    author: 'Ernst Wülcker (ed.)',
    city: {
      cs: 'Frankfurt nad Mohanem',
      en: 'Frankfurt am Main',
      de: 'Frankfurt am Main',
      it: 'Francoforte sul Meno',
    },
    year: 1873,
    href: 'https://archive.org/details/bub_gb_LNVaAAAAcAAJ',
  },
  CHRONIKEN2: {
    name: 'Die Chroniken der fränkischen Städte. Nürnberg II (Die Chroniken der deutschen Städte 2)',
    author: 'Karl Hegel (ed.)',
    city: { cs: 'Lipsko', en: 'Leipzig', de: 'Leipzig', it: 'Lipsia' },
    year: 1864,
    href: 'https://www.digitale-sammlungen.de/de/view/bsb10800625',
  },
  WURDINGER2: {
    name: 'Kriegsgeschichte von Bayern, Franken, Pfalz und Schwaben von 1347 bis 1506 II',
    author: 'Joseph Würdinger',
    city: {
      cs: 'Mnichov',
      en: 'Munich',
      de: 'München',
      it: 'Monaco di Baviera',
    },
    year: 1868,
    href: 'https://www.digitale-sammlungen.de/de/view/bsb11684126',
  },
  PRIEBATSCH2: {
    name: 'Politische Correspondenz des Kurfürsten Albrecht Achilles II',
    author: 'Felix Priebatsch (ed.)',
    city: { cs: 'Lipsko', en: 'Leipzig', de: 'Leipzig', it: 'Lipsia' },
    year: 1897,
    href: 'https://archive.org/details/politischecorres02albr',
  },
  MOBILMACHUNG1477: {
    name: 'Ein Brandenburgischer Mobilmachungsplan aus dem Jahre 1477 (Kriegsgeschichtliche Einzelschriften 3)',
    author: 'Großer Generalstab',
    city: { cs: 'Berlín', en: 'Berlin', de: 'Berlin', it: 'Berlino' },
    year: 1884,
    href: 'https://www.digitale-sammlungen.de/de/view/bsb11655625',
  },
  ALLGARCHIV1: {
    name: 'Allgemeines Archiv für die Geschichtskunde des Preußischen Staates I',
    author: 'Leopold von Ledebur (ed.)',
    city: { cs: 'Berlín', en: 'Berlin', de: 'Berlin', it: 'Berlino' },
    year: 1830,
    href: 'https://www.digitale-sammlungen.de/de/view/bsb10013503',
  },
  JAHNS1889: {
    name: 'Geschichte der Kriegswissenschaften vornehmlich in Deutschland I',
    author: 'Max Jähns',
    city: {
      cs: 'Mnichov – Lipsko',
      en: 'Munich – Leipzig',
      de: 'München – Leipzig',
      it: 'Monaco di Baviera – Lipsia',
    },
    year: 1889,
    href: 'https://archive.org/details/geschichtederkr00jhgoog',
  },
  DRA8: {
    name: 'Deutsche Reichstagsakten unter Kaiser Sigmund. Zweite Abtheilung: 1421–1426 (Deutsche Reichstagsakten VIII)',
    author: 'Dietrich Kerler (ed.)',
    city: 'Gotha',
    year: 1883,
    href: 'https://www.digitale-sammlungen.de/de/view/bsb11833356',
  },
  PALACKY_UB1: {
    name: 'Urkundliche Beiträge zur Geschichte des Hussitenkrieges vom Jahre 1419 an I',
    author: 'František Palacký',
    city: { cs: 'Praha', en: 'Prague', de: 'Prag', it: 'Praga' },
    year: 1873,
    href: 'https://archive.org/details/urkundlichebeitr01pala',
  },
  PALACKY_UB2: {
    name: 'Urkundliche Beiträge zur Geschichte des Hussitenkrieges vom Jahre 1419 an II',
    author: 'František Palacký',
    city: { cs: 'Praha', en: 'Prague', de: 'Prag', it: 'Praga' },
    year: 1873,
    href: 'https://archive.org/details/urkundlichebeitr02pala',
  },
  ANZEIGER1872: {
    name: 'Anzeiger für Kunde der deutschen Vorzeit, Neue Folge XIX',
    author: 'Joseph Würdinger',
    city: {
      cs: 'Norimberk',
      en: 'Nuremberg',
      de: 'Nürnberg',
      it: 'Norimberga',
    },
    year: 1872,
    href: 'https://archive.org/details/anzeigerfrkunde01nrgoog',
  },
  KURZ1825: {
    name: 'Oesterreichs Militärverfassung in älteren Zeiten',
    author: 'Franz Kurz',
    city: { cs: 'Linec', en: 'Linz', de: 'Linz', it: 'Linz' },
    year: 1825,
    href: 'https://archive.org/details/bub_gb_8eEpAAAAYAAJ',
  },
  CGM356: {
    name: 'Cgm 356 (Bayerische Staatsbibliothek München)',
    author: '',
    city: '',
    year: undefined,
    href: 'https://www.digitale-sammlungen.de/de/view/bsb00135889',
  },
  SCHNEIDER1973: {
    name: 'Die deutschen Handschriften der Bayerischen Staatsbibliothek München. Cgm 351–500',
    author: 'Karin Schneider',
    city: 'Wiesbaden',
    year: 1973,
    href: 'https://handschriftenportal.de/search?hspobjectid=HSP-ab1f2e94-505c-3efe-ae59-e996710ab174',
  },
  HOHENWANG: {
    name: 'Red von der Ritterschaft (Vegetius, Epitoma rei militaris), [Augsburg: Johann Wiener, ca. 1475]',
    author: 'Ludwig Hohenwang (transl.)',
    city: '',
    year: undefined,
    href: 'https://www.digitale-sammlungen.de/de/view/bsb00038208',
  },

  GRUNHAGEN1872: {
    name: 'Die Hussitenkämpfe der Schlesier 1420–1435',
    author: 'Colmar Grünhagen',
    city: { cs: 'Vratislav', en: 'Breslau', de: 'Breslau', it: 'Breslavia' },
    year: 1872,
    href: 'https://archive.org/details/bub_gb_s0kJAAAAQAAJ',
  },
  WULF1889: {
    name: 'Die husitische Wagenburg',
    author: 'Maximilian von Wulf',
    city: { cs: 'Berlín', en: 'Berlin', de: 'Berlin', it: 'Berlino' },
    year: 1889,
    href: 'https://www.digitale-sammlungen.de/de/view/bsb11551340',
  },
  PRUB_DH207: {
    name: 'Preußisches Urkundenbuch (online), DH 207',
    author: 'Dieter Heckmann (ed.)',
    city: '',
    year: 2004,
    href: 'https://www.spaetmittelalter.uni-hamburg.de/Urkundenbuch/pub/dh/dh207.htm',
  },
  KDIH: {
    name: 'Katalog der deutschsprachigen illustrierten Handschriften des Mittelalters, Nr. 39.7.4 (Cod. Durlach 18)',
    author: 'Rainer Leng',
    city: '',
    year: undefined,
    href: 'https://kdih.badw.de/datenbank/handschrift/39/7/4',
  },
  MRFH: {
    name: 'Marburger Repertorium zur Übersetzungsliteratur im deutschen Frühhumanismus, Nr. 10475 (Cod. Durlach 18)',
    author: '',
    city: '',
    year: undefined,
    href: 'https://mrfh.de/10475',
  },
  DURLACH18: {
    name: 'Cod. Durlach 18 (Badische Landesbibliothek Karlsruhe)',
    author: '',
    city: '',
    year: undefined,
    href: 'https://digital.blb-karlsruhe.de/id/1609781',
  },
}
