import { MenuItem } from '../types'

export const menuCs: MenuItem[] = [
  { href: '/historicke-pozadi', title: 'Historické pozadí' },
  { href: '/tyrovsti-z-einsiedlu', title: 'Týřovští z Einsiedlu' },
  { href: '/muzsky-odev', title: 'Mužský oděv' },
  { href: '/vyzbroj-a-vystroj', title: 'Výzbroj a výstroj' },
  {
    href: '/ceske-vojenske-rady-a-spisy',
    title: 'České vojenské řády a spisy',
  },
  {
    href: '/nemecke-vojenske-rady-a-spisy',
    title: 'Německé vojenské řády a spisy',
  },
  {
    href: '/prehled-vojenskych-akci',
    title: 'Přehled vojenských akcí',
  },
]

export const menuEn: MenuItem[] = [
  { href: '/historical-background', title: 'Historical background' },
  { href: '/tyrovsky-of-einsiedl', title: 'Týřovský of Einsiedl' },
  { href: '/mens-clothing', title: "Men's clothing" },
  { href: '/arms-and-armour', title: 'Arms and armour' },
  {
    href: '/czech-military-orders-and-writings',
    title: 'Czech military orders and writings',
  },
  {
    href: '/german-military-orders-and-writings',
    title: 'German military orders and writings',
  },
  {
    href: '/military-campaigns',
    title: 'Military campaigns',
  },
]

export const otherCs: MenuItem[] = [
  { href: '/' },
  { href: '/historicke-pozadi/hans-harsdorfer' },
  { href: '/historicke-pozadi/manska-soustava' },
  { href: '/historicke-pozadi/krivokladska-manska-soustava' },
  { href: '/tyrovsti-z-einsiedlu/erb' },
  { href: '/tyrovsti-z-einsiedlu/jindrich-tyrovsky-z-einsiedlu' },
  { href: '/tyrovsti-z-einsiedlu/jost-z-einsiedlu' },
  { href: '/tyrovsti-z-einsiedlu/rozrod' },
  { href: '/muzsky-odev/kabat' },
  { href: '/muzsky-odev/sukne' },
  { href: '/muzsky-odev/spodni-odev' },
  { href: '/muzsky-odev/pokryvky-hlavy' },
  { href: '/muzsky-odev/obuv' },
  { href: '/muzsky-odev/plast' },
  { href: '/vyzbroj-a-vystroj/estok' },
  { href: '/vyzbroj-a-vystroj/tarce' },
  { href: '/vyzbroj-a-vystroj/valecne-kladivo' },
  { href: '/vyzbroj-a-vystroj/zbroj' },
  { href: '/prehled-vojenskych-akci/bavorska-valka' },
  { href: '/prehled-vojenskych-akci/waldshuterkrieg' },
  { href: '/taktika' },
  { href: '/fechtbuch' },
  { href: '/jezdecky-serm' },
  { href: '/kterak-nevytvorit-skupinu-historickeho-sermu' },
  { href: '/zdroje' },
]

export const menuDe: MenuItem[] = [
  { href: '/historischer-hintergrund', title: 'Historischer Hintergrund' },
  { href: '/tyrovsky-von-einsiedl', title: 'Tyrovsky von Einsiedl' },
  { href: '/herrenkleidung', title: 'Herrenkleidung' },
  { href: '/waffen-und-ruestung', title: 'Waffen und Rüstung' },
  {
    href: '/boehmische-militaerordnungen',
    title: 'Böhmische Militärordnungen',
  },
  {
    href: '/deutsche-militaerordnungen',
    title: 'Deutsche Militärordnungen',
  },
  {
    href: '/feldzuege',
    title: 'Feldzüge',
  },
]

export const otherEn: MenuItem[] = [
  { href: '/en' },
  { href: '/historical-background/hans-harsdorfer' },
  { href: '/historical-background/feudal-system' },
  { href: '/historical-background/krivoklat-feudal-system' },
  { href: '/tyrovsky-of-einsiedl/jobst-of-einsiedl' },
  { href: '/tyrovsky-of-einsiedl/henry-of-einsiedl' },
  { href: '/tyrovsky-of-einsiedl/coat-of-arms' },
  { href: '/tyrovsky-of-einsiedl/family-tree' },
  { href: '/mens-clothing/doublet' },
  { href: '/mens-clothing/gown' },
  { href: '/mens-clothing/undergarments' },
  { href: '/mens-clothing/cloak' },
  { href: '/mens-clothing/footwear' },
  { href: '/mens-clothing/headwear' },
  { href: '/arms-and-armour/targe' },
  { href: '/arms-and-armour/estoc' },
  { href: '/arms-and-armour/war-hammer' },
  { href: '/arms-and-armour/armour' },
  { href: '/military-campaigns/bavarian-war' },
  { href: '/military-campaigns/waldshut-war' },
  { href: '/tactics' },
  { href: '/fencing-manual' },
  { href: '/equestrian-fencing' },
  { href: '/how-not-to-create-a-hema-group' },
  { href: '/bibliography' },
  { href: '/saddle' },
]

export const otherDe: MenuItem[] = [
  { href: '/de' },
  { href: '/historischer-hintergrund/hans-harsdorfer' },
  { href: '/historischer-hintergrund/lehnswesen' },
  { href: '/historischer-hintergrund/krivoklater-lehnswesen' },
  { href: '/tyrovsky-von-einsiedl/jobst-von-einsiedl' },
  { href: '/tyrovsky-von-einsiedl/heinrich-von-einsiedl' },
  { href: '/tyrovsky-von-einsiedl/wappen' },
  { href: '/tyrovsky-von-einsiedl/stammbaum' },
  { href: '/herrenkleidung/wams' },
  { href: '/herrenkleidung/rock' },
  { href: '/herrenkleidung/unterkleidung' },
  { href: '/herrenkleidung/mantel' },
  { href: '/herrenkleidung/schuhwerk' },
  { href: '/herrenkleidung/kopfbedeckungen' },
  { href: '/waffen-und-ruestung/panzerstecher' },
  { href: '/waffen-und-ruestung/tartsche' },
  { href: '/waffen-und-ruestung/streithammer' },
  { href: '/waffen-und-ruestung/ruestung' },
  { href: '/feldzuege/bayerischer-krieg' },
  { href: '/feldzuege/waldshuterkrieg' },
  { href: '/taktik' },
  { href: '/fechthandbuch' },
  { href: '/reiterkampf' },
  { href: '/fechtgruppen-leitfaden' },
  { href: '/bibliographie' },
  { href: '/sattel' },
]

export const menuIt: MenuItem[] = [
  { href: '/sfondo-storico', title: 'Sfondo storico' },
  { href: '/tyrovsky-di-einsiedl', title: 'Tyrovsky di Einsiedl' },
  { href: '/abbigliamento-maschile', title: 'Abbigliamento maschile' },
  { href: '/armi-e-armature', title: 'Armi e armature' },
  { href: '/ordinanze-militari-ceche', title: 'Ordinanze militari ceche' },
  {
    href: '/ordinanze-militari-tedesche',
    title: 'Ordinanze militari tedesche',
  },
  { href: '/campagne-militari', title: 'Campagne militari' },
]

export const otherIt: MenuItem[] = [
  { href: '/it' },
  { href: '/sfondo-storico/hans-harsdorfer' },
  { href: '/sfondo-storico/sistema-feudale' },
  { href: '/sfondo-storico/sistema-feudale-di-krivoklat' },
  { href: '/tyrovsky-di-einsiedl/jobst-di-einsiedl' },
  { href: '/tyrovsky-di-einsiedl/enrico-di-einsiedl' },
  { href: '/tyrovsky-di-einsiedl/stemma' },
  { href: '/tyrovsky-di-einsiedl/albero-genealogico' },
  { href: '/abbigliamento-maschile/farsetto' },
  { href: '/abbigliamento-maschile/veste' },
  { href: '/abbigliamento-maschile/biancheria-intima' },
  { href: '/abbigliamento-maschile/mantello' },
  { href: '/abbigliamento-maschile/calzature' },
  { href: '/abbigliamento-maschile/copricapo' },
  { href: '/armi-e-armature/stocco' },
  { href: '/armi-e-armature/targa' },
  { href: '/armi-e-armature/martello-da-guerra' },
  { href: '/armi-e-armature/armatura' },
  { href: '/campagne-militari/guerra-bavarese' },
  { href: '/campagne-militari/guerra-di-waldshut' },
  { href: '/tattica' },
  { href: '/manuale-di-scherma' },
  { href: '/scherma-equestre' },
  { href: '/come-non-creare-un-gruppo-hema' },
  { href: '/bibliografia' },
  { href: '/sella' },
]
